version: '3.8'

services:
  db:
    image: postgres:16
    container_name: task_scheduler_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: task_scheduler_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    container_name: task_scheduler_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${APP_PORT}:3000"
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
